-- ═══════════ KNOWLY RESUMOS — estrutura do catálogo ═══════════
-- Rode este arquivo no SQL Editor do Supabase, depois o 02-seed.sql.

create table if not exists public.livros (
  id             bigint generated by default as identity primary key,
  titulo         text        not null,
  autor          text        not null default 'Edições Premium',
  categoria      text        not null,
  imagem_da_capa text        not null,           -- nome do arquivo no bucket "capas"
  slug           text        not null unique,
  descricao      text,
  preco          numeric(10, 2) not null default 12.90,
  paginas        integer,
  destaque       boolean     not null default false,
  data_criacao   timestamptz not null default now(),
  largura        integer,                        -- dimensões da capa, evitam layout shift
  altura         integer,
  blur           text                            -- placeholder base64 exibido enquanto carrega
);

-- A home filtra por destaque e ordena por data; o detalhe busca por slug.
create index if not exists livros_destaque_idx
  on public.livros (destaque, data_criacao desc);
create index if not exists livros_data_criacao_idx
  on public.livros (data_criacao desc);

-- ═══ Leitura pública, escrita apenas autenticada ═══
alter table public.livros enable row level security;

drop policy if exists "catalogo visivel para todos" on public.livros;
create policy "catalogo visivel para todos"
  on public.livros for select
  to anon, authenticated
  using (true);

drop policy if exists "somente autenticados escrevem" on public.livros;
create policy "somente autenticados escrevem"
  on public.livros for all
  to authenticated
  using (true)
  with check (true);

-- ═══ Bucket público das capas ═══
insert into storage.buckets (id, name, public)
values ('capas', 'capas', true)
on conflict (id) do update set public = true;

drop policy if exists "capas visiveis para todos" on storage.objects;
create policy "capas visiveis para todos"
  on storage.objects for select
  to anon, authenticated
  using (bucket_id = 'capas');

drop policy if exists "somente autenticados enviam capas" on storage.objects;
create policy "somente autenticados enviam capas"
  on storage.objects for all
  to authenticated
  using (bucket_id = 'capas')
  with check (bucket_id = 'capas');
